[versions]
kotlin = "2.4.10"
coroutines = "1.11.0"
grpc = "1.83.1"
grpcKotlin = "1.5.0"
protobuf = "4.35.1"
protobufPlugin = "0.10.0"
mavenPublish = "0.37.0"
okhttp = "4.12.0"
kotlinxSerialization = "1.9.0"
agp = "8.13.2"
androidxTestRunner = "1.6.2"
androidxTestJunit = "1.2.1"

[libraries]
grpc-api = { module = "io.grpc:grpc-api", version.ref = "grpc" }
grpc-protobuf-lite = { module = "io.grpc:grpc-protobuf-lite", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-okhttp = { module = "io.grpc:grpc-okhttp", version.ref = "grpc" }
grpc-inprocess = { module = "io.grpc:grpc-inprocess", version.ref = "grpc" }
grpc-kotlin-stub = { module = "io.grpc:grpc-kotlin-stub", version.ref = "grpcKotlin" }
grpc-generator-java = { module = "io.grpc:protoc-gen-grpc-java", version.ref = "grpc" }
grpc-generator-kotlin = { module = "io.grpc:protoc-gen-grpc-kotlin", version.ref = "grpcKotlin" }
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
